title: Philipp Heinrich
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hej Hej.
  <br><br>
  Analytics & Data Guy. 
  Riding bikes & running for food. 
  <br><br>
  <a href="https://www.linkedin.com/in/philipp-heinrich">CV</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
